# Application name registered in Eureka
spring.application.name=api-gateway

# API Gateway port
server.port=8765

# Eureka Server address
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
