spring.application.name=naming-server

server.port=8761


###########################################
#              EUREKA-SERVER              #
###########################################

# Do not register as client couse this is the server Eureka
eureka.client.register-with-eureka=false

# Eureka Server is the source of the service registry,
# so it does not need to download the registry from another Eureka instance.
eureka.client.fetch-registry=false