spring.application.name=learning-service


server.port=8181

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/devpath_learning
spring.datasource.username=devpath_user
spring.datasource.password=devpath_password

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=*


jwt.secret=devpath-super-secret-key-devpath-super-secret-key